# Site information
site_name: "è¯­æ–‡æ¢æº"
site_url: https://hantang.github.io/cntextbook/
site_author: hantang
site_description: "Chinese textbooks"
copyright: Copyright &copy; 2025 Hantang

# Repository
repo_name: cntextbook
repo_url: https://github.com/hantang/cntextbook/
# edit_uri: tree/main

theme:
  name: material
  custom_dir: overrides
  favicon: static/favicon.ico
  logo: static/logo.png
  language: "zh"

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.footer
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tooltips
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.progress

extra_css:
  - https://cdn.jsdelivr.net/npm/heti@0.9.6/umd/heti.min.css
  # - https://cdn.jsdelivr.net/npm/diff2html/bundles/css/diff2html.min.css
  - static/css/extra.css

extra_javascript:
  # - https://cdnjs.cloudflare.com/ajax/libs/Han/3.2.7/han.min.js
  - https://cdn.jsdelivr.net/npm/heti@0.9.6/umd/heti-addon.min.js
  # - https://cdn.jsdelivr.net/npm/diff2html/bundles/js/diff2html.min.js
  - static/js/remove-space.js
  # - https://unpkg.com/heti/umd/heti-addon.min.js

plugins:
  - search:
      lang:
        - en
        - zh
      separator: '[\s\-,:!=\[\]()"/\u200b]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - meta
  - mkdocs-embed-pdf
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - pymdownx.snippets
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - pymdownx.betterem
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - é¦–é¡µ: index.md
  - è¡¥å……èµ„æ–™:
    - è¯¾ç¨‹æ ‡å‡†:
      - è¯¾ç¨‹æ ‡å‡†/index.md
      - ä¹‰åŠ¡æ•™è‚²:
          - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/index.md
          - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/å‰è¨€.md
          - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/è¯¾ç¨‹æ€§è´¨.md
          - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/è¯¾ç¨‹ç†å¿µ.md
          - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/è¯¾ç¨‹ç›®æ ‡.md
          - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/è¯¾ç¨‹å†…å®¹.md
          - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/å­¦ä¸šè´¨é‡.md
          - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/è¯¾ç¨‹å®æ–½.md
          - é™„å½•:
              - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/é™„å½•/index.md
              - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/é™„å½•/ä¼˜ç§€è¯—æ–‡èƒŒè¯µæ¨èç¯‡ç›®.md
              - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/é™„å½•/å…³äºè¯¾å†…å¤–è¯»ç‰©çš„å»ºè®®.md
              - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/é™„å½•/å…³äºè¯­æ³•ä¿®è¾çŸ¥è¯†çš„è¯´æ˜.md
              - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/é™„å½•/è¯†å­—ã€å†™å­—æ•™å­¦åŸºæœ¬å­—è¡¨.md
              - è¯¾ç¨‹æ ‡å‡†/ä¹‰åŠ¡æ•™è‚²/é™„å½•/ä¹‰åŠ¡æ•™è‚²è¯­æ–‡è¯¾ç¨‹å¸¸ç”¨å­—è¡¨.md
      - æ™®é€šé«˜ä¸­:
          - è¯¾ç¨‹æ ‡å‡†/æ™®é€šé«˜ä¸­/index.md
          - è¯¾ç¨‹æ ‡å‡†/æ™®é€šé«˜ä¸­/å‰è¨€.md
          - è¯¾ç¨‹æ ‡å‡†/æ™®é€šé«˜ä¸­/è¯¾ç¨‹æ€§è´¨ä¸åŸºæœ¬ç†å¿µ.md
          - è¯¾ç¨‹æ ‡å‡†/æ™®é€šé«˜ä¸­/å­¦ç§‘æ ¸å¿ƒç´ å…»ä¸è¯¾ç¨‹ç›®æ ‡.md
          - è¯¾ç¨‹æ ‡å‡†/æ™®é€šé«˜ä¸­/è¯¾ç¨‹ç»“æ„.md
          - è¯¾ç¨‹æ ‡å‡†/æ™®é€šé«˜ä¸­/è¯¾ç¨‹å†…å®¹.md
          - è¯¾ç¨‹æ ‡å‡†/æ™®é€šé«˜ä¸­/å­¦ä¸šè´¨é‡.md
          - è¯¾ç¨‹æ ‡å‡†/æ™®é€šé«˜ä¸­/å®æ–½å»ºè®®.md
          - é™„å½•:
              - è¯¾ç¨‹æ ‡å‡†/æ™®é€šé«˜ä¸­/é™„å½•/index.md
              - è¯¾ç¨‹æ ‡å‡†/æ™®é€šé«˜ä¸­/é™„å½•/å¤è¯—æ–‡èƒŒè¯µæ¨èç¯‡ç›®.md
              - è¯¾ç¨‹æ ‡å‡†/æ™®é€šé«˜ä¸­/é™„å½•/å…³äºè¯¾å†…å¤–è¯»ç‰©çš„å»ºè®®.md
    - "ğŸ”— ä¸­å°å­¦ç”Ÿé˜…è¯»æŒ‡å¯¼ç›®å½•": https://fantribe.github.io/books/edu/
    - "ğŸ”— ä¸­å°å­¦ä¼˜ç§€å¤è¯—æ–‡ç¯‡ç›®": https://fantribe.github.io/books/edu/classic/
